version: '3.8'

services:
    face-storage-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'postgres']
            interval: 10s
            timeout: 5s
            retries: 5

    face-storage-migrator:
        build:
            context: .
            dockerfile: dockerfile.migrator
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        command: ['alembic', 'upgrade', 'head']
        depends_on:
            db:
                condition: service_healthy

    face-storage:
        build:
            context: .
            dockerfile: dockerfile
        depends_on:
            - db
            - rabbitmq
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: always

volumes:
    db_data:
