# Create services namely django server, nginx and postgresql
version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - "30001:6379"
        networks:
            - bsm
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - ./backup/redis_data:/data
        command: redis-server /usr/local/etc/redis/redis.conf

    postgres:
        image: postgres:latest
        ports:
            - "30002:5432"
        networks:
            - bsm
        volumes:
            - ./backup/postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'postgres']
            interval: 5s
            timeout: 5s
            retries: 10

    migration:
        build:
            context: stream/database
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - bsm
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        command: ['alembic', 'upgrade', 'head']

networks:
    bsm:
        driver: bridge
