FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY server/requirements.txt .
RUN pip install -r requirements.txt

COPY database database
COPY server server

CMD ["python", "-m", "server"]
