# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory to /app
WORKDIR /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# Install any needed packages specified in requirements.txt
COPY face/requirements.txt .
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY face face
COPY redis_connection redis_connection

# Run the deepdetection module
CMD ["python", "-m", "face"]
