FROM python:3.11

WORKDIR /app

COPY blob/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY blob/main.py .
COPY blob blob

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
